import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		"why-nadle",
		"introduction",
		{
			type: "category",
			label: "Getting Started",
			items: ["getting-started/installation", "getting-started/playground", "getting-started/features"]
		},
		{
			label: "Guides",
			type: "category",
			items: ["guides/defining-task", "guides/registering-task", "guides/configuring-task", "guides/configuring-nadle"]
		},
		"config-reference",
		{ dirName: "api", type: "autogenerated" }
	]
};

export default sidebars;
