import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		"why-nadle",
		"introduction",
		{
			type: "category",
			label: "Getting Started",
			items: [
				"getting-started/installation",
				"getting-started/quickstart-for-agents",
				"getting-started/playground",
				{
					type: "category",
					label: "Features",
					items: ["getting-started/features/monorepo", "getting-started/features/auto-correction", "getting-started/features/editor-support"]
				}
			]
		},
		{
			type: "category",
			label: "Concepts",
			items: ["concepts/task", "concepts/workspace", "concepts/plugin"]
		},
		{
			label: "Guides",
			type: "category",
			items: [
				"guides/defining-task",
				"guides/registering-task",
				"guides/configuring-task",
				"guides/executing-task",
				"guides/file-operation-tasks",
				"guides/authoring-plugin",
				"guides/configuring-nadle",
				"guides/eslint-plugin",
				{
					label: "Migrating",
					type: "category",
					items: [
						"guides/migrating/from-npm-scripts",
						"guides/migrating/from-turborepo",
						"guides/migrating/from-nx",
						"guides/migrating/from-makefile"
					]
				}
			]
		},
		"config-reference",
		"cli-reference",
		{ dirName: "api", type: "autogenerated" }
	]
};

export default sidebars;
