name: Release Any Commit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "*.md"
      - "packages/docs/**"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "packages/docs/**"
      - "LICENSE"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-any-commit:
    name: Release Any Commit
    if: ${{ github.event.pull_request.draft != true }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Build
        run: nadle build

      - run: pnpm dlx pkg-pr-new publish --bin --comment=update --exclude nadle-vscode-extension './packages/*'
